# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# And then run the script for deploying to nnetligy when the build is successful
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test
      - run: npm run build --if-present

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build
        env:
          NETLIFY_BUILD_HOOK_ID: ${{ secrets.NETLIFY_BUILD_HOOK_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          curl -X POST -d {} "https://api.netlify.com/build_hooks/$NETLIFY_BUILD_HOOK_ID" \
          --header "Content-Type: application/json" \
          --header "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
          --header "Netlify-Site-Id: $NETLIFY_SITE_ID"
